const recipeActionTypes = {
  FETCHING_RECIPE_START: "FETCHING_RECIPE_START",
  FETCHING_RECIPE_SUCCESS: "FETCHING_RECIPE_SUCCESS",
  FETCHING_RECIPE_FAILURE: "FETCHING_RECIPE_FAILURE",
  PLUS_SERVINGS: "PLUS_SERVINGS",
  MINUS_SERVINGS: "MINUS_SERVINGS",
  RENDER_SHOPPING: "RENDER_SHOPPING",
  DELETE_INGREDIENT: "DELETE_INGREDIENT"
}

export default recipeActionTypes;