const recipeActionTypes = {
  FETCHING_RECIPE_START: "FETCHING_RECIPE_START",
  FETCHING_RECIPE_SUCCESS: "FETCHING_RECIPE_SUCCESS",
  FETCHING_RECIPE_FAILURE: "FETCHING_RECIPE_FAILURE",
}

export default recipeActionTypes;